name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        strategy:
            matrix:
                node-version: [16.x, 18.x] #14.x removed because of an open issue with nextjs (https://github.com/vercel/next.js/issues/45052)

        name: Build with ${{matrix.node-version}}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}
                  cache: 'npm'
            - run: npm ci #clean install - meant for use in automated environments
            - run: npm run build-prod

    test:
        strategy:
            matrix:
                node-version: [16.x]
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}
                  cache: 'npm'
            - run: npm ci

            - name: Check types
              run: npm run check-types

            - name: Run unit tests
              run: npm run test

            - name: Run e2e tests
              run: npx percy exec -- npm run e2e:headless
              env:
                  PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
